spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book-api
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true