spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book-api
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            github:
              client-id:
              client-secret:
            facebook:
              client-id:
              client-secret:

jwt:
  secret:
    access: "HGOYioniygOOMIiUJONh"
    refresh: "FBHJFASFBhufhafshjfS"
  expiration:
    access: 10000
    refresh: 1000000
  header: "Authorization"
  enable: true